name: Build and Release

run-name: Build / create_release ${{ github.event.inputs.create_release }}

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for'
        required: true
        default: 'linux,windows,macos'
        type: choice
        options:
          - 'linux,windows,macos'
          - 'linux'
          - 'windows'
          - 'macos'
          - 'linux,windows'
          - 'linux,macos'
          - 'windows,macos'
      create_release:
        description: 'Create a GitHub release (only for manual builds)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rename main to babeldoc_gui (macOS only)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          if [ -f dist/main ]; then
            mv dist/main dist/babeldoc_gui
          fi
